language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"
install:
  - if [ "$TRAVIS_PYTHON_VERSION" = '2.7' -o "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then pip install "pylint>=1.9,<2.0"; else pip install pylint; fi
  - pip install pytest pycodestyle

script:
  - pycodestyle --repeat --ignore=E202,E501,W504 wells
  - pylint --disable=missing-docstring,invalid-name,global-statement,useless-object-inheritance wells
  - py.test wells
